// Generated by CoffeeScript 1.6.3
(function() {
  var Gamemaster, f, f_test, poplinr, the_meaning, the_thought;

  the_thought = void 0;

  the_meaning = void 0;

  console.log(the_thought);

  console.log(the_meaning);

  poplinr = function(whatISay) {
    return console.log(whatISay);
  };

  poplinr("Gamemaster testing room...");

  Gamemaster = (function() {
    function Gamemaster(name, age, mood) {
      this.name = name;
      this.age = age;
      this.mood = mood;
    }

    return Gamemaster;

  })();

  poplinr = new Gamemaster("Ryan Poplin", 23, "So-so");

  console.log(poplinr);

  console.log("" + poplinr.name + " is " + poplinr.mood + ".");

  console.log(function() {});

  f = function(str1) {
    return function(str2) {
      return str1 + " " + str2;
    };
  };

  f_test = f("First...");

  console.log(f_test("Second..."));

}).call(this);
